Support ios10 push notification
moicorp/flutter.plugins pull request #1
Opened 2017-11-07 07:27 UTC by YusukeHata

support ios 10 push notification.

2017-11-07 08:16 UTC, fullfool requested changes
確認おねがいします。

2017-11-07 08:16 UTC, fullfool commented on packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
> +        [_channel invokeMethod:@"onLaunch" arguments:response.notification.request.content.userInfo];
foregroundなので、`onMessage` では？

2017-11-07 08:16 UTC, fullfool commented on packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
> +      [UNUserNotificationCenter currentNotificationCenter].delegate = self;
タイミング的には余り変わらないけど、FirebasePluginの`didFinishLaunchingWithOptions`でやった方がよいかなと思いました。

2017-11-07 08:21 UTC, fullfool commented
`requestNotificationPermissions` のところも `UNUserNotificationCenter` に対応した方がよいと思います。

```
  if ([@"requestNotificationPermissions" isEqualToString:method]) {
      if (@available(iOS 10, *)) {
          UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
          [center requestAuthorizationWithOptions:(UNAuthorizationOptionAlert + UNAuthorizationOptionSound)
                                completionHandler:^(BOOL granted, NSError *_Nullable error) {
                                    result(nil);
                                }];
      }else{
          // iOS10未満の処理
      }

```

2017-11-07 08:29 UTC, fullfool commented on packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
> +      [UNUserNotificationCenter currentNotificationCenter].delegate = self;
> must set the value of this property before your app finishes launching

https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649522-delegate?language=objc

関数名まで指定されてるので念のため。
（pluginのinitもまさにそこから呼ばれてはいるのですけど）

2017-11-07 13:08 UTC, YusukeHata commented on packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
> +        [_channel invokeMethod:@"onLaunch" arguments:response.notification.request.content.userInfo];
通知へのユーザーのアクションが起こった場合に呼び出されるので `onMessage` は適切ではないかと思います。
`willPresentNotification` は通知受信時に呼び出されるのでそちらに`onMessage` を追加しました。

2017-11-07 13:09 UTC, YusukeHata commented
@fullfool 確認お願いします。

2017-11-07 16:11 UTC, fullfool commented on packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
> +        [_channel invokeMethod:@"onLaunch" arguments:response.notification.request.content.userInfo];
たしかに。
onMessage = 「foreground時のメッセージ」という認識だったけど、今回はユーザーのアクションが伴うので、`onMessage` はこの場合適切じゃないですね。
（実際にはここでは、フォアグラウンド、バッググラウンド `onResume`、起動時 `onLaunch` 全部のケースが発生しうるわけか）

2017-11-07 16:12 UTC, fullfool approved these changes
👍

2022-03-09 03:10 UTC, fullfool commented
閉じます

2022-03-09 03:10 UTC, closed without merging